package com.menwic.practica_apuestas.GUI;

import com.menwic.practica_apuestas.manejador_apuesta.Apuesta;
import com.menwic.practica_apuestas.manejador_apuesta.EstructuraApuesta;
import com.menwic.practica_apuestas.manejador_archivo.FileManagment;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Luis
 */
public class PanelApuestas extends javax.swing.JPanel {

    /**
     * Creates new form panelApuestas
     */
    public PanelApuestas() {
        initComponents();
        customInit();
    }

    private void customInit() {
        JTextField a = new JTextField();
        textMonto.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ((c < '0' || c > '9') && c != KeyEvent.VK_BACK_SPACE) {
                    e.consume();
                }
            }
        });
    }

    private void saveFile() {
        EstructuraApuesta bets = EstructuraApuesta.getEstructuraApuesta();
        if (FileManagment.seleccionarDir() && FileManagment.guardar(bets.getRechazadas())) {
            JOptionPane.showMessageDialog(this, "Archivo Guardado Exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error - Guardar Archivo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textMonto = new javax.swing.JTextField();
        combo1ro = new javax.swing.JComboBox<>();
        combo2do = new javax.swing.JComboBox<>();
        combo3ro = new javax.swing.JComboBox<>();
        combo4to = new javax.swing.JComboBox<>();
        combo5to = new javax.swing.JComboBox<>();
        combo10mo = new javax.swing.JComboBox<>();
        combo8vo = new javax.swing.JComboBox<>();
        combo9no = new javax.swing.JComboBox<>();
        combo6to = new javax.swing.JComboBox<>();
        combo7mo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buttonVerify = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 102));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(675, 437));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nick Apostador =");

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Monto apuesta =");

        combo1ro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo1ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1roActionPerformed(evt);
            }
        });

        combo2do.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo2do.setSelectedIndex(1);
        combo2do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2doActionPerformed(evt);
            }
        });

        combo3ro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo3ro.setSelectedIndex(2);
        combo3ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3roActionPerformed(evt);
            }
        });

        combo4to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo4to.setSelectedIndex(3);
        combo4to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4toActionPerformed(evt);
            }
        });

        combo5to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo5to.setSelectedIndex(4);
        combo5to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo5toActionPerformed(evt);
            }
        });

        combo10mo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo10mo.setSelectedIndex(9);
        combo10mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo10moActionPerformed(evt);
            }
        });

        combo8vo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo8vo.setSelectedIndex(7);
        combo8vo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo8voActionPerformed(evt);
            }
        });

        combo9no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo9no.setSelectedIndex(8);
        combo9no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo9noActionPerformed(evt);
            }
        });

        combo6to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo6to.setSelectedIndex(5);
        combo6to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo6toActionPerformed(evt);
            }
        });

        combo7mo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo7mo.setSelectedIndex(6);
        combo7mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo7moActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("1ro.");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("2do.");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("3ro.");

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("4to.");

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("5to.");

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("6to.");

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("7mo.");

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("8vo.");

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("9no.");

        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("10mo.");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Agregar apuesta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Cargar Archivo (.txt .csv)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonVerify.setBackground(new java.awt.Color(0, 0, 0));
        buttonVerify.setForeground(new java.awt.Color(255, 255, 255));
        buttonVerify.setText("Cerrar Apuestas");
        buttonVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerifyActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel13.setText("Carga o Ingreso de Apuestas");

        jLabel14.setText("Nota: Cargue un archivo o ingrese manualmente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo1ro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo9no, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo5to, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo6to, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo2do, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo10mo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo7mo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo3ro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo4to, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo8vo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(197, 197, 197))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textMonto))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(combo2do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(combo3ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(combo4to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combo5to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo6to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(combo7mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(combo8vo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo9no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(combo10mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo1roActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1roActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1roActionPerformed

    private void combo2doActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2doActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo2doActionPerformed

    private void combo3roActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3roActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo3roActionPerformed

    private void combo4toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo4toActionPerformed

    private void combo5toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo5toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo5toActionPerformed

    private void combo10moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo10moActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo10moActionPerformed

    private void combo8voActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo8voActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo8voActionPerformed

    private void combo9noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo9noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo9noActionPerformed

    private void combo6toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo6toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo6toActionPerformed

    private void combo7moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo7moActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo7moActionPerformed

    private void buttonVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerifyActionPerformed
        // TODO add your handling code here:
        EstructuraApuesta apuestas = EstructuraApuesta.getEstructuraApuesta();
        if (!apuestas.validado()) {
            int value = JOptionPane.showConfirmDialog(this, "(Confirmar) Cerrar apuestas", "Verificar", JOptionPane.YES_NO_OPTION);
            if (value == 0) {
                apuestas.validar();
                //saveFile();
            }
        } else {
            saveFile();
        }
    }//GEN-LAST:event_buttonVerifyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (!EstructuraApuesta.getEstructuraApuesta().validado()) {
            String nombre = textName.getText();
            String montoSt = textMonto.getText();
            if (nombre.matches("\\w+") && montoSt.matches("[1-9]\\d*")) { //Pattern
                int monto = 0;
                try {
                    monto = Integer.parseInt(montoSt);
                } catch (Exception ex) {
                    monto = -1;
                }
                if (monto <= 0) {
                    JOptionPane.showMessageDialog(this, "Verifique el monto");
                } else {
                    int primero = Integer.parseInt(combo1ro.getSelectedItem().toString());
                    int segundo = Integer.parseInt(combo2do.getSelectedItem().toString());
                    int tercero = Integer.parseInt(combo3ro.getSelectedItem().toString());
                    int cuarto = Integer.parseInt(combo4to.getSelectedItem().toString());
                    int quinto = Integer.parseInt(combo5to.getSelectedItem().toString());
                    int sexto = Integer.parseInt(combo6to.getSelectedItem().toString());
                    int septimo = Integer.parseInt(combo7mo.getSelectedItem().toString());
                    int octavo = Integer.parseInt(combo8vo.getSelectedItem().toString());
                    int noveno = Integer.parseInt(combo9no.getSelectedItem().toString());
                    int decimo = Integer.parseInt(combo10mo.getSelectedItem().toString());
                    int positions[] = {primero, segundo, tercero, cuarto, quinto,
                        sexto, septimo, octavo, noveno, decimo};
                    Apuesta bet = new Apuesta(nombre, monto, positions);
                    EstructuraApuesta.getEstructuraApuesta().addSinVerificar(bet);
                    JOptionPane.showMessageDialog(this, "Apuesta Agregada Exitosamente");
                }
                textName.setText("");
                textMonto.setText("");
                combo1ro.setSelectedIndex(0);
                combo2do.setSelectedIndex(1);
                combo3ro.setSelectedIndex(2);
                combo4to.setSelectedIndex(3);
                combo5to.setSelectedIndex(4);
                combo6to.setSelectedIndex(5);
                combo7mo.setSelectedIndex(6);
                combo8vo.setSelectedIndex(7);
                combo9no.setSelectedIndex(8);
                combo10mo.setSelectedIndex(9);
                SwingUtilities.updateComponentTreeUI(this);
            } else {
                JOptionPane.showMessageDialog(this, "Error en campos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Apuestas Cerradas");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        EstructuraApuesta bets = EstructuraApuesta.getEstructuraApuesta();
        if (bets.validado()) {
            JOptionPane.showMessageDialog(this, "Apuestas Cerradas");
        } else if (FileManagment.abrir()) {
            JOptionPane.showMessageDialog(this, "Archivo Cargado Exitosamente");
            //Bets.getBets().getNoVerified().escribir();
            //System.out.println("------------------");
            //System.out.println("------------------");
        } else {
            JOptionPane.showMessageDialog(this, "Error - Cargar Archivo");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVerify;
    private javax.swing.JComboBox<String> combo10mo;
    private javax.swing.JComboBox<String> combo1ro;
    private javax.swing.JComboBox<String> combo2do;
    private javax.swing.JComboBox<String> combo3ro;
    private javax.swing.JComboBox<String> combo4to;
    private javax.swing.JComboBox<String> combo5to;
    private javax.swing.JComboBox<String> combo6to;
    private javax.swing.JComboBox<String> combo7mo;
    private javax.swing.JComboBox<String> combo8vo;
    private javax.swing.JComboBox<String> combo9no;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textMonto;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables
}
